export enum ErrorEnum {
    INVALID_PARAMETERS = "INVALID_PARAMETERS",
    GENERIC_SERVER_ERROR = "GENERIC_SERVER_ERROR",
    INVALID_TOKEN = "INVALID_TOKEN",
    INVALID_DATABASE_OBJECT = "INVALID_DATABASE_OBJECT",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    NO_ACTIVE_CHANNELS = "NO_ACTIVE_CHANNELS",
    INVALID_ID = "INVALID_ID"
}
